### ISSUE TITLE
Visual Studio Compiler

### ISSUE THREAD

**Issue by MakerLS** [mrdude2478/IPS_Patch_Creator#11]
Hello.
First of all, thank you for your work.

Secondly...
I am unable to compile in Visual Studio... is there a tutorial?
It's not that my knowledge in Visual Studio is spectacular either.

Thanks again

**Comment by BeckysFootSlave** [comment]
Yeah, same Problem here!

Installed the four packages with exactla the same Version you wrote, but I can do what I want always get 2 Errors because of these lines (both):

client.ConnectTimeout = 1000; //wait 1 second

Don't know what the hell is wrong with it?

Would be awesome to know how to compile the exe file, or is it possible to compile it no matter what errors come up?

Thanks in advance!

**Comment by KrasParker** [comment]
Hi, kindly if it was possible I wanted to know how to fill everything in

**Comment by mrdude2478** [comment]
Closing as you figured it out.
